spring.application.name=Onlinr_Book_Management_Crud
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

# Database URL
spring.datasource.url=jdbc:mysql:///mvc_db

# Database Username
spring.datasource.username=root

#server port
server.port=1111

# Database Password
spring.datasource.password=Shivam@22

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate DDL
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect (optional in Spring Boot 3.x)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=shivam
#spring.security.user.password=12345
